# This section will create a secret in the Kubernetes cluster.
# We need this for private docker repos.
apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: DeploymentConsult/DeploymentConsult.WebHost/Dockerfile
type: kubernetes.io/dockerconfigjson
---
# This section will create a deployment in the Kubernetes cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    app: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: hatxh/deployment-consult:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
---
# This section will create a service in the Kubernetes cluster
# so that the deployment can be accessed from the outside
apiVersion: v1
kind: Service
metadata:
  name: deployment-test
  labels:
    app: test-app
spec:
  type: LoadBalancer
  selector:
    app: test-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
